### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by enzohnnn** [Stephen-Schuster/cse15l-lab-reports#1]

**Comment by enzohnnn** [comment]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
  - I think you could add more to the last step "Remote Running Optimization" by including more screenshots of relevant of examples of terminal commands, trying out the steps we suggested in the writeup, etc. 
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Great lab report! Just a few fixes and it's perfect. Easy to read.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by Stephen-Schuster** [comment]
finished fixing issues

**Comment by enzohnnn** [comment]
Nice fixes! In the future, please don't edit the grader's issue so we can easily go back and see what we need to look at.
